### PR TITLE
Major API Rework

### PR DESCRIPTION
**Pull request by JeffreyCA**
The WatCard website changed a few months ago which broke the app as well as many other applications that rely on WatCard data. I made two libraries, [watcard-java-api](https://github.com/JeffreyCA/watcard-java-api) and [watcard-android](https://github.com/JeffreyCA/watcard-android) which uses an updated way, via web-scraping, to retrieve WatCard balance and transaction data.

Here is my attempt to update WatBalance using my new library to replace the existing non-functional code as a result of the recent backend changes. I ended up removing a lot of code that no longer work because the API URLs changed.

I also updated many of the dependencies and resolved most deprecated pieces of code. I also reworked the Settings activity a bit, adding a Toolbar and tweaking the colours a bit.

### CODE REVIEW

**Comment by xbhatnag** [comment]
Hey Jeffrey.
Thanks a lot for pointing out the changes! Will review this soon!
As a suggestion, could you split the changes into more PRs if possible? That makes it easy to review.

**Comment by JeffreyCA** [comment]
Sorry, I just read your edit. I'm not sure how to do that.

Here is a working APK I generated.
[app-debug.apk.zip](https://github.com/xbhatnag/WatBalance/files/681592/app-debug.apk.zip)

**Comment by xbhatnag** [comment]
There are many ways to do this. One is to create a new branch and then cherry pick commits which are unrelated.

**Comment by JeffreyCA** [comment]
Is it possible to review the changes as it is right now? My commits weren't very organized and cherry-picking causes a lot of conflicts I don't know how to deal with.

**Pull request closed without merging**
